puts "The students of my cohort at Makers Academy"
puts "-------------"
puts "Tiger Woods"
puts "Darth Vador"
puts "Charly Sheen"
puts "Jay Z"
puts "Ryan Leslie"
puts "Rick Ross"
puts "John Mayer"
puts "Ed Sheeran"
puts "Nina Simone"
